function prob = hist_prob(x, pdf)
% Compute probabilities of input data in the discrete distribution.
%
% Input:
%   x [1xN (double)] N input data values from the interval [0, 1]
%   pdf [1xM (double)] PDF of the discrete distribution for M values
%     generated by linspace(0, 1, M)
%
% Output:
%   prob [1xN (double)] probabilities of N input values in the discrete
%     distribution specified by the given PDF; each input value is assigned
%     probability of the closest value from linspace(0, 1, M) 

% TODO: Replace with your own implementation.
LN = linspace(0,1,256);
LNT = LN';
for i = 1:length(x)
    X = x(i);
    for j = 1:length(LNT)
        Y = LNT(j);
        if X - Y == 0 || Y - X < 0.0000000000000001
            prob(i) = pdf(j);
        end
    end
end
end
